// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package sqlc

import (
	"net/netip"

	"github.com/gofrs/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Author struct {
	ID uuid.UUID  `json:"id"`
	Ip netip.Addr `json:"ip"`
}

type Comment struct {
	ID        int32              `json:"id"`
	Post      int32              `json:"post"`
	Author    uuid.UUID          `json:"author"`
	Reply     pgtype.Int4        `json:"reply"`
	Content   string             `json:"content"`
	CreatedAt pgtype.Timestamptz `json:"createdAt"`
}

type CommentLike struct {
	Author  uuid.UUID `json:"author"`
	Comment int32     `json:"comment"`
}

type Post struct {
	ID        int32              `json:"id"`
	Author    uuid.UUID          `json:"author"`
	CreatedAt pgtype.Timestamptz `json:"createdAt"`
	Content   string             `json:"content"`
}

type PostLike struct {
	Author uuid.UUID `json:"author"`
	Post   int32     `json:"post"`
}
